name: Build and Deploy
on:
  push:
    branches:
      - master
    schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        
    - name: Setup hugo
        run: peaceiris/actions-hugo@v2
        
    - name: Jalankan hugo
        run: hugo
        
    - uses: pulimento/github-action-hugo-deploy-to-firebase@master
      with:
        firebase-token: ${{ secrets.FIREBASE_TOKEN }}

        


