name: Build and Deploy
  push:
    branches:
      - master
    schedule:
    - cron: "0 0 * * *"
    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
   - name: Build
        run: hugo     
    - uses: pulimento/github-action-hugo-deploy-to-firebase@master
      with:
        firebase-token: ${{ secrets.secret_firebase_token }}
